server:
    port: 8080

spring:
    data:
        mongodb:
          username: "danilencomihailamdaris"
          password: "PRAu3NUXG73PXPLK"
          uri: "mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@newsaggregator.iahqf.mongodb.net/?retryWrites=true&w=majority&appName=NewsAggregator"
          database: "car-service"