server:
  port: 8081

spring:
  data:
    mongodb:
      username: ${MONGODB_USERNAME:mihaildanilenco}
      password: ${MONGODB_PASSWORD}
      uri: "mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@learningdb.qe33ksl.mongodb.net/car-service?retryWrites=true&w=majority&appName=LearningDB"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/car-service-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/car-service-realm/protocol/openid-connect/certs}

keycloak:
  realm: ${KEYCLOAK_REALM:car-service-realm}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  resource: ${KEYCLOAK_RESOURCE:car-service-client}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true
  bearer-only: true
  admin:
    client-id: admin-cli
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG

scheduler:
  cron:
    appointment-slot-generator: "0 0 0 * * *"