server:
  port: 8080

spring:
  data:
    mongodb:
      username: "mihaildanilenco"
      password: "zgZr8uGhEXwEBggg"
      uri: "mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@learningdb.qe33ksl.mongodb.net/?retryWrites=true&w=majority&appName=LearningDB"
      database: "car-service"

jwt:
  key: 3mB%9V@fK!mP#G7zWrXj2LoqA8UdNcYbTfQwErTyUiOpAsDfGhJkLzXcVbNmQwErT
  access-token-expiration: 3600000
  refresh-token-expiration: 172800000

logging:
    level:
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.springframework.data.mongodb: DEBUG

scheduler:
  cron:
    appointment-slot-generator: "0 0 0 * * *"